version: '3.9'

services:
  poc-mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  poc-zookeeper:
    image: "confluentinc/cp-zookeeper:5.2.1"
    ports:
      - "2181:2181"
    networks:
      - kafka-poc
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  poc-kafka:
    image: "confluentinc/cp-enterprise-kafka:5.2.1"
    ports:
      - '9092:9092'
      - '29094:29094'
    depends_on:
      - poc-zookeeper
    networks:
      - kafka-poc
    restart: on-failure
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: poc-zookeeper:2181
      KAFKA_LISTENERS: LISTENER_INTERNAL_TRAFFIC://poc-kafka:29092,LISTENER_DOCKER_HOST://poc-kafka:9092,LISTENER_OUTSIDE_TRAFFIC://poc-kafka:29094
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL_TRAFFIC://poc-kafka:29092,LISTENER_DOCKER_HOST://localhost:9092,LISTENER_OUTSIDE_TRAFFIC://dns-for-traffic-from-outside:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL_TRAFFIC:PLAINTEXT,LISTENER_DOCKER_HOST:PLAINTEXT,LISTENER_OUTSIDE_TRAFFIC:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL_TRAFFIC
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 1

  poc-schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - poc-zookeeper
      - poc-kafka
    ports:
      - "8081:8081"
    networks:
      - kafka-poc
    restart: on-failure
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'poc-zookeeper:2181'

networks:
  kafka-poc:
    driver: bridge

volumes:
  mongodb_data:
    driver: local